# Generated by Django 3.1.4 on 2020-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0, null=True)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black')], max_length=20, null=True)),
                ('size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('2XL', 'Double XL'), ('S', 'Small'), ('XL', 'Extra Large')], max_length=20, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
            ],
        ),
    ]
