# Generated by Django 3.1.4 on 2020-12-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='cloth_main_photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Red', 'Red')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('2XL', 'Double XL'), ('XL', 'Extra Large'), ('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=20, null=True),
        ),
    ]
